## dev config

## server
server:
  port: 8089

## spring config
spring:
  datasource:
    url: "jdbc:mysql://172.16.140.10:3306/stock_alert?useUnicode=true&characterEncoding=utf8\
      &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\
      &useSSL=true&allowMultiQueries=true&autoReconnect=true&nullCatalogMeansCurrent=true\
      &nullCatalogMeansCurrent=true"
    username: root
    password: "Qwert12345!"
  mail:
    host: smtp.sina.com
    port: 465
    username: xxx@sina.com
    password: xxx
    protocol: smtps
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
          tls: true
  # rabbitmq
  rabbitmq:
    host: 172.16.140.10
    port: 5672
    username: rabbitmqadmin
    password: rootpass100
  ## redis
  redis:
    database: 1
    host: 172.16.140.10
    port: 7749
    password: 21cde022-a5da-626e-c8f4-04c99ed3a181
    connect-timeout: 60s
    timeout: 120s
    lettuce:
      pool:
        max-wait: 60s
        max-active: 20
        max-idle: 10
        min-idle: 5

## 股票数据接口
stockApi:
  apiAddress: http://hq.sinajs.cn/list=